### ISSUE TITLE
Redirects crash the server

### ISSUE THREAD

**Issue by jcea** [bahamas10/node-fs-caching-server#4]
A 301 HTTP response will kill the server. The right approach would be to follow the redirection. In fact, if the redirect is permanent (301), you could store the cached file under the original path, to about hitting the server again.

See this thread for details: https://smartos.topicbox.com/groups/smartos-discuss/T69931a6cd66a7f2b/strange-crash-in-fs-caching-server

**Comment by bahamas10** [comment]
thank you for debugging this! i'll look into a solution for this

**Comment by bahamas10** [comment]
fixed in `v1.0.0` that was just published.  thanks again!
